# Generated by Django 3.0.7 on 2020-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosaicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('CL', 'color'), ('GR', 'greyscale'), ('BW', 'black & white')], default='CL', max_length=2)),
            ],
        ),
    ]
