# Generated by Django 3.0.7 on 2020-06-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgconvert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='mosaic',
        ),
    ]
