# Generated by Django 3.0.7 on 2020-06-29 22:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgconvert', '0003_mosaic_mosaic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='mosaic',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
